title: .glosa lab
url: "https://glosa-lab.github.io"
baseurl: ""

# Configuração de Resumos
excerpt_separator: "<!--mais-->"

# Como você está criando o tema, garanta que o Jekyll ignore o que não deve
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
